
export const users = [
  { id: 1, name: 'Alice', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Ok, vou verificar.', lastMessageTime: '10:40 AM', unread: 2 },
  { id: 2, name: 'Carlos', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'O relatório está pronto.', lastMessageTime: '9:30 AM', unread: 0 },
  { id: 3, name: 'Beatriz', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Podemos marcar uma reunião?', lastMessageTime: 'Ontem', unread: 0 },
  { id: 4, name: 'Daniel', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Anexei os documentos.', lastMessageTime: 'Ontem', unread: 1 },
  { id: 5, name: 'Fernanda', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'Qual o prazo final?', lastMessageTime: '2 dias atrás', unread: 0 },
  { id: 6, name: 'Gustavo', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'Entendido.', lastMessageTime: '2 dias atrás', unread: 0 },
];

export const messages = {
  '1': [
    { sender: 'me', text: 'Olá Alice, tudo bem? Conseguiu ver a documentação da emenda parlamentar?', timestamp: '10:30 AM' },
    { sender: 'Alice', text: 'Oi! Tudo bem. Sim, estou analisando agora.', timestamp: '10:32 AM' },
    { sender: 'Alice', text: 'Parece que falta a assinatura do gestor. Você pode confirmar?', timestamp: '10:35 AM' },
    { sender: 'me', text: 'Claro, vou checar com ele e te retorno.', timestamp: '10:36 AM' },
    { sender: 'Alice', text: 'Ok, vou verificar.', timestamp: '10:40 AM' },
  ],
  '2': [
    { sender: 'Carlos', text: 'O relatório está pronto.', timestamp: '9:30 AM' },
  ],
  '3': [
      { sender: 'Beatriz', text: 'Podemos marcar uma reunião?', timestamp: 'Ontem' },
  ]
};

export const conventions = [
  {
      ano: 2013,
      numero: '677800',
      situacao: 'ADIMPLENTE',
      uf: 'DF',
      municipio: 'BRASÍLIA',
      proponente: 'VALEC Engenharia, Construções e Ferrovias SA',
      convenente: 'VALEC ENGENHARIA, CONSTRUÇÕES E FERROVIAS SA',
      objeto: 'FORTALECIMENTO INSTITUCIONAL DA EMPRESA DE PLANEJAMENTO E LOGÍSTICA POR MEIO DA PROPOSIÇÃO DE MODE...',
      valorConvenio: 'R$ 58.991.596,21',
      valorLiberado: 'R$ 53.447.422,80',
      saldoALiberar: 'R$ 5.544.173,41',
      inicioVigencia: '26/12/2013',
      fimVigencia: '31/12/2025',
      diasRestantes: 'Restam 141 dias',
      percentualLiberado: 90.60
  },
  {
      ano: 2021,
      numero: '1AAGNZ',
      situacao: 'ADIMPLENTE',
      uf: 'SP',
      municipio: 'SÃO PAULO',
      proponente: 'VALEC Engenharia, Construções e Ferrovias SA',
      convenente: 'CFI - CORPORAÇÃO FINANCEIRA INTERNACIONAL',
      objeto: 'ACORDO DE PARCERIA 01/2021-ELABORAÇÃO DE ESTUDOS DE VIABILIDADE TÉCNICA, ECONÔMICO-FINANCEIRA, AMBIE...',
      valorConvenio: 'R$ 21.154.683,15',
      valorLiberado: 'R$ 15.412.716,03',
      saldoALiberar: 'R$ 5.741.967,12',
      inicioVigencia: '29/11/2021',
      fimVigencia: '29/06/2026',
      diasRestantes: '321 dias restantes',
      percentualLiberado: 72.86
  },
  {
      ano: 2021,
      numero: '1AAHAF',
      situacao: 'ADIMPLENTE',
      uf: 'DF',
      municipio: 'BRASÍLIA',
      proponente: 'VALEC Engenharia, Construções e Ferrovias SA',
      convenente: 'BANCO INTERAMERICANO DE DESENVOLVIMENTO',
      objeto: 'ACORDO DE PARCERIA 02/2021 PARA ELABORAR ESTUDOS DE VIABILIDADE TÉCNICA, ECONÔMICO-FINANCEIRA, AMBIE...',
      valorConvenio: 'R$ 30.804.079,98',
      valorLiberado: 'R$ 14.347.545,54',
      saldoALiberar: 'R$ 16.456.534,44',
      inicioVigencia: '15/12/2021',
      fimVigencia: '15/06/2027',
      diasRestantes: '672 dias restantes',
      percentualLiberado: 46.58
  },
  {
      ano: 2025,
      numero: '976278',
      situacao: 'EM EXECUÇÃO',
      uf: 'RP',
      municipio: 'CURITIBA',
      proponente: 'Universidade Tecnológica Federal do Paraná',
      convenente: 'FUNDAÇÃO DE APOIO A EDUCAÇÃO, PESQUISA E DESENVOLVIMENTO',
      objeto: 'Oferta de Turma de Mestrado Interinstitucional Minter em Planejamento e Governança Pública, devida...',
      valorConvenio: 'R$ 740.827,50',
      valorLiberado: 'R$ 200.000,00',
      saldoALiberar: 'R$ 540.827,50',
      inicioVigencia: '29/07/2025',
      fimVigencia: '13/03/2028',
      diasRestantes: 'Restam 944 dias',
      percentualLiberado: 27.00
  },
  {
      ano: 2024,
      numero: '937124',
      situacao: 'EM EXECUÇÃO',
      uf: 'RP',
      municipio: 'CURITIBA',
      proponente: 'Universidade Tecnológica Federal do Paraná',
      convenente: 'FUNDAÇÃO DE APOIO A EDUCAÇÃO, PESQUISA E DESENVOLVIMENTO',
      objeto: 'Execução do TED 04/2022 junto à Funasa - Apoio à elaboração de Planos de Segurança da Água (PSA) par...',
      valorConvenio: 'R$ 976.636,62',
      valorLiberado: 'R$ 782.285,94',
      saldoALiberar: 'R$ 194.350,68',
      inicioVigencia: '19/03/2024',
      fimVigencia: '07/07/2026',
      diasRestantes: 'Restam 329 dias',
      percentualLiberado: 80.10
  },
  {
      ano: 2023,
      numero: '940849',
      situacao: 'PRESTAÇÃO DE CONTAS EM ANÁLISE',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDAÇÃO GUIMARÃES DUQUE',
      objeto: 'Oferecer curso de qualificação profissional na região semiárida potiguar, promovendo a qualificação...',
      valorConvenio: 'R$ 1.000.000,00',
      valorLiberado: 'R$ 795.139,84',
      saldoALiberar: 'R$ 204.860,16',
      inicioVigencia: '01/06/2023',
      fimVigencia: '31/03/2025',
      diasRestantes: '-133 dias restantes',
      percentualLiberado: 79.51
  },
];

export const amendments = [
  { 
    id: '201830490006',
    ano: 2018,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0006',
    localidade: 'Nacional',
    funcao: 'Saúde',
    subfuncao: 'Assistência hospitalar e ambulatorial',
    valorEmpenhado: 'R$ 100.000,00',
    valor: 'R$ 100.000,00',
    valorPago: 'R$ 100.000,00',
    valorLiberar: 'R$ 0,00',
    porcentagem: 100,
    status: 'Aprovada'
  },
  { 
    id: '201830490004',
    ano: 2018,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0004',
    localidade: 'RORAIMA (UF)',
    funcao: 'Saúde',
    subfuncao: 'Administração geral',
    valorEmpenhado: 'R$ 6.486.136,00',
     valor: 'R$ 6.486.136,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 6.486.136,00',
    porcentagem: 0,
    status: 'Rejeitada'
  },
  { 
    id: '201930490003',
    ano: 2019,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0003',
    localidade: 'RORAIMA (UF)',
    funcao: 'Saúde',
    subfuncao: 'Assistência hospitalar e ambulatorial',
    valorEmpenhado: 'R$ 7.610.387,00',
    valor: 'R$ 7.610.387,00',
    valorPago: 'R$ 7.610.387,00',
    valorLiberar: 'R$ 0,00',
    porcentagem: 100,
    status: 'Aprovada'
  },
  { 
    id: '201630300002',
    ano: 2016,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0002',
    localidade: 'MÚLTIPLO',
    funcao: 'Urbanismo',
    subfuncao: 'Assistência comunitária',
    valorEmpenhado: 'R$ 342.143,00',
    valor: 'R$ 342.143,00',
    valorPago: 'R$ 171.071,00',
    valorLiberar: 'R$ 171.072,00',
    porcentagem: 50,
    status: 'Em análise'
  },
  { 
    id: '201730490002',
    ano: 2017,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0002',
    localidade: 'MÚLTIPLO',
    funcao: 'Saúde',
    subfuncao: 'Saneamento básico urbano',
    valorEmpenhado: 'R$ 2.343.887,00',
    valor: 'R$ 2.343.887,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 2.343.887,00',
    porcentagem: 0,
    status: 'Pendente'
  },
  {
    id: '201830490005',
    ano: 2018,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0005',
    localidade: 'RORAIMA (UF)',
    funcao: 'Saúde',
    subfuncao: 'Atenção básica',
    valorEmpenhado: 'R$ 799.942,00',
    valor: 'R$ 799.942,00',
    valorPago: 'R$ 196.000,00',
    valorLiberar: 'R$ 603.942,00',
    porcentagem: 24.5,
    status: 'Em análise'
  },
  {
    id: '201930490001',
    ano: 2019,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0001',
    localidade: 'RORAIMA (UF)',
    funcao: 'Defesa nacional',
    subfuncao: 'Assistência comunitária',
    valorEmpenhado: 'R$ 7.610.387,00',
    valor: 'R$ 7.610.387,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 7.610.387,00',
    porcentagem: 0,
    status: 'Rejeitada'
  },
  {
    id: '201730490003',
    ano: 2017,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0003',
    localidade: 'Nacional',
    funcao: 'Saúde',
    subfuncao: 'Assistência hospitalar e ambulatorial',
    valorEmpenhado: 'R$ 100.000,00',
    valor: 'R$ 100.000,00',
    valorPago: 'R$ 100.000,00',
    valorLiberar: 'R$ 0,00',
    porcentagem: 100,
    status: 'Aprovada'
  },
  {
    id: '201730490004',
    ano: 2017,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0004',
    localidade: 'MÚLTIPLO',
    funcao: 'Saúde',
    subfuncao: 'Saneamento básico rural',
    valorEmpenhado: 'R$ 4.092.563,00',
    valor: 'R$ 4.092.563,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 4.092.563,00',
    porcentagem: 0,
    status: 'Pendente'
  },
  {
    id: '201630300001',
    ano: 2016,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0001',
    localidade: 'RORAIMA (UF)',
    funcao: 'Defesa nacional',
    subfuncao: 'Assistência comunitária',
    valorEmpenhado: 'R$ 6.471.218,00',
    valor: 'R$ 6.471.218,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 6.471.218,00',
    porcentagem: 0,
    status: 'Rejeitada'
  }
];

