

export const users = [
  { id: 1, name: 'Alice', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Ok, vou verificar.', lastMessageTime: '10:40 AM', unread: 2 },
  { id: 2, name: 'Carlos', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'O relatório está pronto.', lastMessageTime: '9:30 AM', unread: 0 },
  { id: 3, name: 'Beatriz', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Podemos marcar uma reunião?', lastMessageTime: 'Ontem', unread: 0 },
  { id: 4, name: 'Daniel', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Anexei os documentos.', lastMessageTime: 'Ontem', unread: 1 },
  { id: 5, name: 'Fernanda', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'Qual o prazo final?', lastMessageTime: '2 dias atrás', unread: 0 },
  { id: 6, name: 'Gustavo', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'Entendido.', lastMessageTime: '2 dias atrás', unread: 0 },
];

export const messages = {
  '1': [
    { sender: 'me', text: 'Olá Alice, tudo bem? Conseguiu ver a documentação da emenda parlamentar?', timestamp: '10:30 AM' },
    { sender: 'Alice', text: 'Oi! Tudo bem. Sim, estou analisando agora.', timestamp: '10:32 AM' },
    { sender: 'Alice', text: 'Parece que falta a assinatura do gestor. Você pode confirmar?', timestamp: '10:35 AM' },
    { sender: 'me', text: 'Claro, vou checar com ele e te retorno.', timestamp: '10:36 AM' },
    { sender: 'Alice', text: 'Ok, vou verificar.', timestamp: '10:40 AM' },
  ],
  '2': [
    { sender: 'Carlos', text: 'O relatório está pronto.', timestamp: '9:30 AM' },
  ],
  '3': [
      { sender: 'Beatriz', text: 'Podemos marcar uma reunião?', timestamp: 'Ontem' },
  ]
};

export type Convention = {
    ano: number;
    numero: string;
    situacao: string;
    uf: string;
    municipio: string;
    proponente: string;
    convenente: string;
    objeto: string;
    valorConvenio: string;
    valorLiberado: string;
    saldoALiberar: string;
    inicioVigencia: string;
    fimVigencia: string;
    diasRestantes: string;
    percentualLiberado: number;
};

export const staticConventions: Convention[] = [
    {
        ano: 2023,
        numero: "947852",
        situacao: "Em execução",
        uf: "SP",
        municipio: "São Paulo",
        proponente: "PREFEITURA MUNICIPAL DE SAO PAULO",
        convenente: "Ministério da Saúde",
        objeto: "Construção de Unidade Básica de Saúde no bairro Jardim das Flores.",
        valorConvenio: "R$ 1.500.000,00",
        valorLiberado: "R$ 750.000,00",
        saldoALiberar: "R$ 750.000,00",
        inicioVigencia: "01/01/2023",
        fimVigencia: "31/12/2024",
        diasRestantes: "580",
        percentualLiberado: 50
    },
    {
        ano: 2022,
        numero: "935641",
        situacao: "Adimplente",
        uf: "RJ",
        municipio: "Rio de Janeiro",
        proponente: "GOVERNO DO ESTADO DO RIO DE JANEIRO",
        convenente: "Ministério da Educação",
        objeto: "Aquisição de equipamentos de informática para escolas da rede estadual.",
        valorConvenio: "R$ 2.000.000,00",
        valorLiberado: "R$ 2.000.000,00",
        saldoALiberar: "R$ 0,00",
        inicioVigencia: "15/03/2022",
        fimVigencia: "14/03/2023",
        diasRestantes: "0",
        percentualLiberado: 100
    },
    {
        ano: 2023,
        numero: "951234",
        situacao: "Aguardando Prestação de Contas",
        uf: "MG",
        municipio: "Belo Horizonte",
        proponente: "PREFEITURA MUNICIPAL DE BELO HORIZONTE",
        convenente: "Ministério da Cultura",
        objeto: "Realização do Festival de Inverno de Belo Horizonte.",
        valorConvenio: "R$ 500.000,00",
        valorLiberado: "R$ 500.000,00",
        saldoALiberar: "R$ 0,00",
        inicioVigencia: "01/06/2023",
        fimVigencia: "31/08/2023",
        diasRestantes: "0",
        percentualLiberado: 100
    },
    {
        ano: 2024,
        numero: "963321",
        situacao: "Prestação de Contas em Análise",
        uf: "BA",
        municipio: "Salvador",
        proponente: "SECRETARIA DE TURISMO DA BAHIA",
        convenente: "Ministério do Turismo",
        objeto: "Apoio a projetos de desenvolvimento do turismo local.",
        valorConvenio: "R$ 800.000,00",
        valorLiberado: "R$ 400.000,00",
        saldoALiberar: "R$ 400.000,00",
        inicioVigencia: "01/02/2024",
        fimVigencia: "31/01/2025",
        diasRestantes: "215",
        percentualLiberado: 50
    },
     {
        ano: 2021,
        numero: "921122",
        situacao: "Cancelado",
        uf: "AM",
        municipio: "Manaus",
        proponente: "PREFEITURA MUNICIPAL DE MANAUS",
        convenente: "Ministério do Meio Ambiente",
        objeto: "Projeto de preservação de nascentes na área urbana de Manaus.",
        valorConvenio: "R$ 300.000,00",
        valorLiberado: "R$ 0,00",
        saldoALiberar: "R$ 300.000,00",
        inicioVigencia: "10/05/2021",
        fimVigencia: "09/05/2022",
        diasRestantes: "0",
        percentualLiberado: 0
    },
    {
      ano: 2013,
      numero: '677800',
      situacao: 'ADIMPLENTE',
      uf: 'DF',
      municipio: 'BRASÍLIA',
      proponente: 'VALEC Engenharia, Construções e Ferrovias S.A.',
      convenente: 'PROGRAMA DAS NACOES UNIDAS PARA O DESENVOLVIMENTO - PNUD',
      objeto: 'FORTALECIMENTO INSTITUCIONAL DA EMPRESA DE PLANEJAMENTO E LOGISTICA POR MEIO DA PROPOSIÇÃO DE MODE...',
      valorConvenio: 'R$58.991.596,21',
      valorLiberado: 'R$53.447.422,80',
      saldoALiberar: 'R$5.544.173,41',
      inicioVigencia: '26/12/2013',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 90.6
    },
    {
      ano: 2021,
      numero: '1AAGNZ',
      situacao: 'ADIMPLENTE',
      uf: 'SP',
      municipio: 'SÃO PAULO',
      proponente: 'VALEC Engenharia, Construções e Ferrovias S.A.',
      convenente: 'CFI - CORPORACAO FINANCEIRA INTERNACIONAL',
      objeto: 'ACORDO DE PARCERIA 01/2021-ELABORAÇÃO DE ESTUDOS DE VIABILIDADE TÉCNICA, ECONÔMICO-FINANCEIRA, AMBIE...',
      valorConvenio: 'R$21.154.683,15',
      valorLiberado: 'R$15.412.716,03',
      saldoALiberar: 'R$5.741.967,12',
      inicioVigencia: '29/11/2021',
      fimVigencia: '29/06/2026',
      diasRestantes: '317 dias restantes',
      percentualLiberado: 72.86
    },
    {
      ano: 2021,
      numero: '1AAHAF',
      situacao: 'ADIMPLENTE',
      uf: 'DF',
      municipio: 'BRASÍLIA',
      proponente: 'VALEC Engenharia, Construções e Ferrovias S.A.',
      convenente: 'BANCO INTERAMERICANO DE DESENVOLVIMENTO',
      objeto: 'ACORDO DE PARCERIA 02/2021 PARA ELABORAR ESTUDOS DE VIABILIDADE TÉCNICA, ECONÔMICO-FINANCEIRA, AMBIE...',
      valorConvenio: 'R$30.804.079,98',
      valorLiberado: 'R$14.347.545,54',
      saldoALiberar: 'R$16.456.534,44',
      inicioVigencia: '15/12/2021',
      fimVigencia: '15/06/2027',
      diasRestantes: '668 dias restantes',
      percentualLiberado: 46.58
    },
    {
      ano: 2025,
      numero: '976278',
      situacao: 'EM EXECUÇÃO',
      uf: 'PR',
      municipio: 'CURITIBA',
      proponente: 'Universidade Tecnológica Federal do Paraná',
      convenente: 'FUNDACAO DE APOIO A EDUCACAO, PESQUISA E DESENVOLVIMENTO CIENTIFICO E TECNOLOGICO DA UNIVERSIDADE TECNOLOGICA FEDERAL DO PARANA',
      objeto: 'Oferta de Turma de Mestrado interinstitucional Minter em Planejamento e Governanca Publica, devida...',
      valorConvenio: 'R$740.827,50',
      valorLiberado: 'R$200.000,00',
      saldoALiberar: 'R$540.827,50',
      inicioVigencia: '29/07/2025',
      fimVigencia: '13/03/2028',
      diasRestantes: '940 dias restantes',
      percentualLiberado: 27
    },
    {
      ano: 2024,
      numero: '937124',
      situacao: 'EM EXECUÇÃO',
      uf: 'PR',
      municipio: 'CURITIBA',
      proponente: 'Universidade Tecnológica Federal do Paraná',
      convenente: 'FUNDACAO DE APOIO A EDUCACAO, PESQUISA E DESENVOLVIMENTO CIENTIFICO E TECNOLOGICO DA UNIVERSIDADE TECNOLOGICA FEDERAL DO PARANA',
      objeto: 'Execucao de TED 04/2022 junto a Funasa - Apoio a elaboracao de Planos de Seguranca da agua (PSA) par...',
      valorConvenio: 'R$976.636,62',
      valorLiberado: 'R$782.285,94',
      saldoALiberar: 'R$194.350,68',
      inicioVigencia: '19/03/2024',
      fimVigencia: '07/07/2026',
      diasRestantes: '325 dias restantes',
      percentualLiberado: 80.1
    },
    {
      ano: 2023,
      numero: '940849',
      situacao: 'PRESTAÇÃO DE CONTAS EM ANÁLISE',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Ofertar curso de qualificacao profissional na regiao semiarida potiguar, promovendo a qualificacao t...',
      valorConvenio: 'R$1.000.000,00',
      valorLiberado: 'R$795.139,84',
      saldoALiberar: 'R$204.860,16',
      inicioVigencia: '01/06/2023',
      fimVigencia: '31/03/2025',
      diasRestantes: '-137 dias restantes',
      percentualLiberado: 79.51
    },
    {
      ano: 2021,
      numero: '907214',
      situacao: 'PRESTAÇÃO DE CONTAS ENVIADA PARA ANÁLISE',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Melhorar o nivel de formacao dos discentes dos cursos de engenharias e tambem informar estudantes de...',
      valorConvenio: 'R$165.000,00',
      valorLiberado: 'R$120.574,15',
      saldoALiberar: 'R$44.425,85',
      inicioVigencia: '01/07/2021',
      fimVigencia: '01/03/2025',
      diasRestantes: '-167 dias restantes',
      percentualLiberado: 73.08
    },
    {
      ano: 2023,
      numero: '952839',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Contribuir para a sustentabilidade da criacao de camarao marinho de produtores de base comunitaria a...',
      valorConvenio: 'R$948.970,00',
      valorLiberado: 'R$948.970,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '30/12/2023',
      fimVigencia: '12/12/2025',
      diasRestantes: '118 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2021,
      numero: '907145',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Este projeto de extensao tem como objetivo principal contribuir qualitativamente e quantitativamente...',
      valorConvenio: 'R$157.900,00',
      valorLiberado: 'R$113.474,15',
      saldoALiberar: 'R$44.425,85',
      inicioVigencia: '30/08/2021',
      fimVigencia: '30/12/2025',
      diasRestantes: '136 dias restantes',
      percentualLiberado: 71.86
    },
    {
      ano: 2019,
      numero: '886044',
      situacao: 'PRESTAÇÃO DE CONTAS ENVIADA PARA ANÁLISE',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Promover o desenvolvimento de conteudo, de criacao e producao de cursos de extensao modalidade EAD e...',
      valorConvenio: 'R$2.217.038,44',
      valorLiberado: 'R$2.217.038,44',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '12/12/2019',
      fimVigencia: '19/03/2025',
      diasRestantes: '-149 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '941717',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'O projeto tem o objetivo, planejar e instalar o Nucleo de Equoterapia do Semiarido - NESA, tendo com...',
      valorConvenio: 'R$3.600.022,00',
      valorLiberado: 'R$3.600.022,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '21/06/2023',
      fimVigencia: '21/07/2026',
      diasRestantes: '339 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2020,
      numero: '890269',
      situacao: 'PRESTAÇÃO DE CONTAS EM ANÁLISE',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Neste projeto, propoe-se a criacao do Centro de Linguas do Semiarido, a ser referido doravante como ...',
      valorConvenio: 'R$706.809,10',
      valorLiberado: 'R$570.864,20',
      saldoALiberar: 'R$135.944,90',
      inicioVigencia: '05/02/2020',
      fimVigencia: '02/12/2024',
      diasRestantes: '-256 dias restantes',
      percentualLiberado: 80.77
    },
    {
      ano: 2021,
      numero: '916791',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Viabilizar produtos derivados dos subprodutos do sal; - Diminuir 30% o descarte das Aguas mAe; - Ger...',
      valorConvenio: 'R$600.000,00',
      valorLiberado: 'R$600.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '15/10/2021',
      fimVigencia: '29/09/2026',
      diasRestantes: '409 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2021,
      numero: '907219',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Este projeto tendo como cabeca de cartaz o projeto de uma aeronave pode assim ser utilizado para mos...',
      valorConvenio: 'R$155.600,00',
      valorLiberado: 'R$111.174,15',
      saldoALiberar: 'R$44.425,85',
      inicioVigencia: '01/07/2021',
      fimVigencia: '30/12/2025',
      diasRestantes: '136 dias restantes',
      percentualLiberado: 71.45
    },
    {
      ano: 2024,
      numero: '955614',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Realizar um programa de iniciacao, aperfeicoamento e treinamento em natacao para criancas e adolesce...',
      valorConvenio: 'R$216.420,00',
      valorLiberado: 'R$177.315,00',
      saldoALiberar: 'R$39.105,00',
      inicioVigencia: '15/02/2024',
      fimVigencia: '15/02/2026',
      diasRestantes: '183 dias restantes',
      percentualLiberado: 81.93
    },
    {
      ano: 2023,
      numero: '940477',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Fortalecer as atividades de seguranca no transito, proporcionando aos motoqueiros e motociclistas um...',
      valorConvenio: 'R$1.000.000,00',
      valorLiberado: 'R$1.000.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '05/06/2023',
      fimVigencia: '03/09/2025',
      diasRestantes: '18 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '947373',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Desenvolver tecnologias e inovacao socioambientais que garantam a autonomia das mulheres camponesas ...',
      valorConvenio: 'R$3.663.263,60',
      valorLiberado: 'R$3.076.807,61',
      saldoALiberar: 'R$586.455,99',
      inicioVigencia: '25/10/2023',
      fimVigencia: '01/09/2027',
      diasRestantes: '746 dias restantes',
      percentualLiberado: 83.99
    },
    {
      ano: 2024,
      numero: '959783',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Promover a melhoria da qualidade genetica do rebanho bovino leiteiro da cidade de Mossoro-RN, atrave...',
      valorConvenio: 'R$350.000,00',
      valorLiberado: 'R$350.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '03/06/2024',
      fimVigencia: '03/06/2027',
      diasRestantes: '656 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2022,
      numero: '936516',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'objeto a formacao de licenciados, bachareis, tecnologos e/ou acertificacao de especialistas, mediant...',
      valorConvenio: 'R$719.211,46',
      valorLiberado: 'R$526.587,00',
      saldoALiberar: 'R$192.624,46',
      inicioVigencia: '05/12/2022',
      fimVigencia: '04/12/2026',
      diasRestantes: '475 dias restantes',
      percentualLiberado: 73.22
    },
    {
      ano: 2023,
      numero: '943861',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'O Baja, alem de abranger grande area da universidade, em termos de aumentar os conhecimentos e forma...',
      valorConvenio: 'R$125.000,00',
      valorLiberado: 'R$80.574,15',
      saldoALiberar: 'R$44.425,85',
      inicioVigencia: '31/08/2023',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 64.46
    },
    {
      ano: 2022,
      numero: '924989',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Criacao de um nucleo de assessoria tecnica em desenvolvimento produtivo para Micro e pequenas empres...',
      valorConvenio: 'R$844.381,00',
      valorLiberado: 'R$844.381,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '15/06/2022',
      fimVigencia: '15/01/2026',
      diasRestantes: '152 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2020,
      numero: '899564',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'Convenio entre Universidade Federal Rural do Semi-Arido UFERSA, e Fundacao Guimaraes Duque FGD, pa...',
      valorConvenio: 'R$5.195.490,30',
      valorLiberado: 'R$5.195.490,30',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '05/06/2020',
      fimVigencia: '06/02/2026',
      diasRestantes: '174 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '947336',
      situacao: 'EM EXECUÇÃO',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDACAO GUIMARAES DUQUE',
      objeto: 'O presente Plano de Trabalho tem como objeto a formacao de licenciados, bachareis, tecnologos e/ou a...',
      valorConvenio: 'R$2.330.940,00',
      valorLiberado: 'R$1.313.690,00',
      saldoALiberar: 'R$1.017.250,00',
      inicioVigencia: '25/10/2023',
      fimVigencia: '25/02/2027',
      diasRestantes: '558 dias restantes',
      percentualLiberado: 56.36
    },
    {
      ano: 2024,
      numero: '969590',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente Contrato tem como objeto a prestacao de suporte administrativo e financeiro da fundacao d...',
      valorConvenio: 'R$1.366.618,00',
      valorLiberado: 'R$1.366.618,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '30/12/2024',
      fimVigencia: '30/12/2026',
      diasRestantes: '501 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '955853',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente CONVENIO tem por objeto a contratacao da FAPUR para gerir financeira e administrativament...',
      valorConvenio: 'R$750.000,00',
      valorLiberado: 'R$750.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '26/04/2024',
      fimVigencia: '26/04/2029',
      diasRestantes: '1349 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '962276',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O repasse de recursos financeiros para gerir financeira e administrativamente o Projeto de Pesquisa,...',
      valorConvenio: 'R$3.120.000,00',
      valorLiberado: 'R$1.570.000,00',
      saldoALiberar: 'R$1.550.000,00',
      inicioVigencia: '19/06/2024',
      fimVigencia: '18/06/2026',
      diasRestantes: '306 dias restantes',
      percentualLiberado: 50.32
    },
    {
      ano: 2024,
      numero: '965940',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'Realizar uma analise abrangente e detalhada do setor agropecuario na regiao de Tres Rios com o intui...',
      valorConvenio: 'R$203.000,00',
      valorLiberado: 'R$203.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '15/08/2024',
      fimVigencia: '15/08/2025',
      diasRestantes: '0 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '969979',
      situacao: 'EM EXECUÇÃO',
      uf: 'CE',
      municipio: 'FORTALEZA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'INSTITUTO BR ARTE',
      objeto: 'Promover o desenvolvimento regional e a inclusao social por meio da capacitacao profissional de mora...',
      valorConvenio: 'R$1.683.000,00',
      valorLiberado: 'R$841.500,00',
      saldoALiberar: 'R$841.500,00',
      inicioVigencia: '30/12/2024',
      fimVigencia: '30/12/2025',
      diasRestantes: '136 dias restantes',
      percentualLiberado: 50
    },
    {
      ano: 2024,
      numero: '969405',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente Convenio tem como objeto a prestacao de suporte administrativo e financeiro da fundacao d...',
      valorConvenio: 'R$980.743,00',
      valorLiberado: 'R$326.914,00',
      saldoALiberar: 'R$653.829,00',
      inicioVigencia: '29/11/2024',
      fimVigencia: '29/11/2027',
      diasRestantes: '835 dias restantes',
      percentualLiberado: 33.33
    },
    {
      ano: 2024,
      numero: '967008',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O projeto resulta de uma solicitacao do MDHC em resposta ao exarado no Inquerito Civil n.o 1.30.001....',
      valorConvenio: 'R$520.000,00',
      valorLiberado: 'R$400.000,00',
      saldoALiberar: 'R$120.000,00',
      inicioVigencia: '26/09/2024',
      fimVigencia: '27/05/2026',
      diasRestantes: '284 dias restantes',
      percentualLiberado: 76.92
    },
    {
      ano: 2024,
      numero: '966025',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente CONVENIO tem por objeto a contratacao da FAPUR para gerir financeira e administrativament...',
      valorConvenio: 'R$6.575.000,00',
      valorLiberado: 'R$2.700.000,00',
      saldoALiberar: 'R$3.875.000,00',
      inicioVigencia: '08/10/2024',
      fimVigencia: '08/01/2026',
      diasRestantes: '145 dias restantes',
      percentualLiberado: 41.06
    },
    {
      ano: 2023,
      numero: '954032',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente CONVENIO tem por objeto a contratacao da FAPUR para gerir financeira e administrativament...',
      valorConvenio: 'R$1.303.985,00',
      valorLiberado: 'R$993.750,00',
      saldoALiberar: 'R$310.235,00',
      inicioVigencia: '30/12/2023',
      fimVigencia: '26/12/2028',
      diasRestantes: '1228 dias restantes',
      percentualLiberado: 76.21
    },
    {
      ano: 2024,
      numero: '966410',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente Convenio tem como objeto a prestacao de suporte administrativo e financeiro da fundacao d...',
      valorConvenio: 'R$576.001,65',
      valorLiberado: 'R$576.001,65',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '22/08/2024',
      fimVigencia: '22/07/2027',
      diasRestantes: '705 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '972186',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'RIO DE JANEIRO',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'INSTITUTO NACIONAL DE ASSISTENCIA, TRABALHO, OPORTUNIDADES E SAUDE',
      objeto: 'Implementacao e desenvolvimento do Projeto Capacita Sao Goncalo, visando a qualificacao de jovens e ...',
      valorConvenio: 'R$1.870.000,00',
      valorLiberado: 'R$724.050,58',
      saldoALiberar: 'R$1.145.949,42',
      inicioVigencia: '30/12/2024',
      fimVigencia: '30/12/2025',
      diasRestantes: '136 dias restantes',
      percentualLiberado: 38.72
    },
    {
      ano: 2024,
      numero: '966024',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente CONVENIO tem por objeto o repasse de recurso financeiro a CONVENENTE para gerir financeir...',
      valorConvenio: 'R$797.000,00',
      valorLiberado: 'R$589.500,00',
      saldoALiberar: 'R$207.500,00',
      inicioVigencia: '06/08/2024',
      fimVigencia: '06/02/2026',
      diasRestantes: '174 dias restantes',
      percentualLiberado: 73.96
    },
    {
      ano: 2024,
      numero: '969129',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente tem como objeto a prestacao de suporte administrativo e financeiro da fundacao de apoio n...',
      valorConvenio: 'R$443.642,42',
      valorLiberado: 'R$443.642,42',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '08/11/2024',
      fimVigencia: '08/11/2025',
      diasRestantes: '84 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '968163',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'ITAGUAÍ',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'ASSOCIACAO CASA DO PAI - P.A.I',
      objeto: 'Implementacao do projeto CARAVANA PET para controlar a populacao de caes e gatos e prevenir zoonoses...',
      valorConvenio: 'R$1.000.000,00',
      valorLiberado: 'R$1.000.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '27/12/2024',
      fimVigencia: '27/01/2026',
      diasRestantes: '164 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2021,
      numero: '924865',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O Objetivo geral deste projeto e a Regularizacao Fundiaria de toda FNSC, transferindo para quem de d...',
      valorConvenio: 'R$11.618.504,00',
      valorLiberado: 'R$10.618.504,00',
      saldoALiberar: 'R$1.000.000,00',
      inicioVigencia: '31/12/2021',
      fimVigencia: '30/03/2026',
      diasRestantes: '226 dias restantes',
      percentualLiberado: 91.39
    },
    {
      ano: 2023,
      numero: '953641',
      situacao: 'EM EXECUÇÃO',
      uf: 'RJ',
      municipio: 'SEROPÉDICA',
      proponente: 'Universidade Federal Rural do Rio de Janeiro',
      convenente: 'FUNDACAO DE APOIO A PESQ. CIENTIF. TECN. DA UFRRJ',
      objeto: 'O presente CONVENIO tem por objeto a contratacao da FAPUR para gerir financeira e administrativament...',
      valorConvenio: 'R$14.200.000,00',
      valorLiberado: 'R$10.700.000,00',
      saldoALiberar: 'R$3.500.000,00',
      inicioVigencia: '26/12/2023',
      fimVigencia: '09/01/2026',
      diasRestantes: '146 dias restantes',
      percentualLiberado: 75.35
    },
    {
      ano: 2022,
      numero: '920487',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Implementar unidades de referencia em sistema intensivo para Litopenaeus vannamei e Oreochromis nilo...',
      valorConvenio: 'R$175.000,00',
      valorLiberado: 'R$175.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '20/12/2022',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '968490',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'O objeto consiste na organizacao, planejamento e execucao do Seminario Internacional deEducacao Esco...',
      valorConvenio: 'R$500.000,00',
      valorLiberado: 'R$500.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '25/10/2024',
      fimVigencia: '31/10/2025',
      diasRestantes: '76 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '973475',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Formacao em compras publicas da agricultura familiar, a fim de capacitar associacoes e cooperativas ...',
      valorConvenio: 'R$2.100.000,00',
      valorLiberado: 'R$2.100.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '27/01/2025',
      fimVigencia: '18/12/2026',
      diasRestantes: '489 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '975332',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Realizacao das atividades de formacao dos Agentes em Economia Popular e Solidaria do Programa Paul S...',
      valorConvenio: 'R$6.197.510,00',
      valorLiberado: 'R$1.100.000,00',
      saldoALiberar: 'R$5.097.510,00',
      inicioVigencia: '17/06/2025',
      fimVigencia: '30/06/2026',
      diasRestantes: '318 dias restantes',
      percentualLiberado: 17.75
    },
    {
      ano: 2025,
      numero: '976211',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Viabilizar o planejamento e Implementacao de Tendas e infraestrutura da 77a SBPC.',
      valorConvenio: 'R$234.345,00',
      valorLiberado: 'R$234.345,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '11/07/2025',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '976473',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Realizacao do II ENCONTRO NACIONAL DE AGRICULTURA URBANA em Recife-PE, para um publico estimado em 3...',
      valorConvenio: 'R$169.914,00',
      valorLiberado: 'R$169.914,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '24/07/2025',
      fimVigencia: '24/12/2025',
      diasRestantes: '130 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '954866',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Desenvolver a transio agroecolgica em assentamentos rurais, a partir da formao dos assentados e asse...',
      valorConvenio: 'R$25.813.699,22',
      valorLiberado: 'R$600.000,00',
      saldoALiberar: 'R$25.213.699,22',
      inicioVigencia: '13/05/2024',
      fimVigencia: '29/12/2026',
      diasRestantes: '500 dias restantes',
      percentualLiberado: 2.32
    },
    {
      ano: 2024,
      numero: '969429',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Implementacao do projeto de pesquisa intitulado Robotica Educacional e de Competicaono Ensino Formal...',
      valorConvenio: 'R$500.000,00',
      valorLiberado: 'R$500.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '20/11/2024',
      fimVigencia: '31/10/2025',
      diasRestantes: '76 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '976130',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Viabilizar o planejamento e Implementacao de Tendas e infraestrutura da 77a SBPC.',
      valorConvenio: 'R$500.000,00',
      valorLiberado: 'R$500.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '03/07/2025',
      fimVigencia: '01/07/2026',
      diasRestantes: '319 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '968362',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Apoiar a construcao do conhecimento, por meio de estudos e pesquisas voltadas para uma melhor compre...',
      valorConvenio: 'R$1.662.444,89',
      valorLiberado: 'R$938.574,45',
      saldoALiberar: 'R$723.870,44',
      inicioVigencia: '31/10/2024',
      fimVigencia: '31/08/2027',
      diasRestantes: '745 dias restantes',
      percentualLiberado: 56.46
    },
    {
      ano: 2023,
      numero: '951950',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Avaliacao da Politica e do Plano Nacional de Atendimento Socioeducativo - Sinase, com foco no Plano ...',
      valorConvenio: 'R$1.939.768,00',
      valorLiberado: 'R$1.939.768,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '12/12/2023',
      fimVigencia: '30/01/2026',
      diasRestantes: '167 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '960446',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Promocao e fortalecimento de 60 cooperativas, associacoes e empreendimentossolidarios da agricultura...',
      valorConvenio: 'R$4.977.662,56',
      valorLiberado: 'R$4.977.662,56',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '12/06/2024',
      fimVigencia: '14/02/2026',
      diasRestantes: '182 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '970942',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Assessoramento das redes municipais de educacao, em parceria com a Secretaria de Educacao Basica do ...',
      valorConvenio: 'R$4.683.827,40',
      valorLiberado: 'R$1.210.680,00',
      saldoALiberar: 'R$3.473.147,40',
      inicioVigencia: '09/12/2024',
      fimVigencia: '31/01/2027',
      diasRestantes: '533 dias restantes',
      percentualLiberado: 25.85
    },
    {
      ano: 2024,
      numero: '969624',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Mobilizar uma rede de atores do semiarido brasileiro e de regioes para a melhor atuacao e implementa...',
      valorConvenio: 'R$18.620.028,00',
      valorLiberado: 'R$5.739.731,93',
      saldoALiberar: 'R$12.880.296,07',
      inicioVigencia: '31/12/2024',
      fimVigencia: '08/02/2028',
      diasRestantes: '906 dias restantes',
      percentualLiberado: 30.83
    },
    {
      ano: 2025,
      numero: '975389',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'O objeto consiste na organizacao, planejamento e execucao do Seminario Internacional de Educacao Esc...',
      valorConvenio: 'R$300.000,00',
      valorLiberado: 'R$300.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '11/07/2025',
      fimVigencia: '30/11/2025',
      diasRestantes: '106 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '951807',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Avaliacao e revisao do Plano Decenal Nacional dos Direitos de Criancas e Adolescentes.',
      valorConvenio: 'R$3.000.000,00',
      valorLiberado: 'R$3.000.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '12/12/2023',
      fimVigencia: '30/07/2026',
      diasRestantes: '348 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '950807',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Atualizar o PAN Brasil Mobilizar uma rede de atores do semiarido brasileiro e de regioes que sofrem ...',
      valorConvenio: 'R$2.426.450,00',
      valorLiberado: 'R$2.426.450,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '06/12/2023',
      fimVigencia: '30/09/2025',
      diasRestantes: '45 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '952122',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'A pesca e uma atividade de grande importancia ecologica, economica e social. A tomada de decisao par...',
      valorConvenio: 'R$6.987.158,76',
      valorLiberado: 'R$4.554.737,34',
      saldoALiberar: 'R$2.432.421,42',
      inicioVigencia: '29/02/2024',
      fimVigencia: '31/12/2026',
      diasRestantes: '502 dias restantes',
      percentualLiberado: 65.19
    },
    {
      ano: 2024,
      numero: '969843',
      situacao: 'EM EXECUÇÃO',
      uf: 'PE',
      municipio: 'RECIFE',
      proponente: 'Universidade Federal Rural de Pernambuco',
      convenente: 'FUNDACAO APOLONIO SALES DE DESENVOLVIMENTO EDUCACIONAL',
      objeto: 'Mobilizacao de estrategias para fortalecimento do Sistema Nacional de Seguranca Alimentar e Nutricio...',
      valorConvenio: 'R$3.097.441,00',
      valorLiberado: 'R$600.000,00',
      saldoALiberar: 'R$2.497.441,00',
      inicioVigencia: '27/11/2024',
      fimVigencia: '30/11/2027',
      diasRestantes: '836 dias restantes',
      percentualLiberado: 19.37
    },
    {
      ano: 2025,
      numero: '973866',
      situacao: 'EM EXECUÇÃO',
      uf: 'MG',
      municipio: 'TEÓFILO OTONI',
      proponente: 'Universidade Federal dos Vales do Jequitinhonha e Mucuri',
      convenente: 'APJ APRENDER PRODUZIR JUNTOS',
      objeto: 'Producao e distribuicao de refeicoes nutricionalmente balanceadas, originadas deprocessos seguros e ...',
      valorConvenio: 'R$535.187,40',
      valorLiberado: 'R$246.083,30',
      saldoALiberar: 'R$289.104,10',
      inicioVigencia: '29/04/2025',
      fimVigencia: '29/10/2025',
      diasRestantes: '74 dias restantes',
      percentualLiberado: 45.98
    },
    {
      ano: 2023,
      numero: '942209',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'O Convenio tem por finalidade a conjugacao de esforcos para realizacao do Projeto intitulado Projeto...',
      valorConvenio: 'R$991.259,00',
      valorLiberado: 'R$495.635,00',
      saldoALiberar: 'R$495.624,00',
      inicioVigencia: '13/07/2023',
      fimVigencia: '13/07/2027',
      diasRestantes: '696 dias restantes',
      percentualLiberado: 50
    },
    {
      ano: 2024,
      numero: '968958',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Cidadania e politicas publicas: construindo uma gestao participativa dos Territorios Quilombolas no ...',
      valorConvenio: 'R$300.000,00',
      valorLiberado: 'R$300.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '08/11/2024',
      fimVigencia: '08/11/2025',
      diasRestantes: '84 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2022,
      numero: '932519',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'O presente Convenio tem por finalidade a conjugacao de esforcos para realizacao do Projeto deDesenvo...',
      valorConvenio: 'R$573.500,00',
      valorLiberado: 'R$273.000,00',
      saldoALiberar: 'R$300.500,00',
      inicioVigencia: '06/12/2022',
      fimVigencia: '06/12/2026',
      diasRestantes: '477 dias restantes',
      percentualLiberado: 47.6
    },
    {
      ano: 2024,
      numero: '970163',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Curso de Crises Ambientais na Atencao Primaria a Saude',
      valorConvenio: 'R$1.219.000,00',
      valorLiberado: 'R$1.219.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '13/12/2024',
      fimVigencia: '24/12/2025',
      diasRestantes: '130 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2022,
      numero: '931323',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'O projeto visa avancar na implementacao da abordagem de aprendizagem centrada no aluno a partir de m...',
      valorConvenio: 'R$57.524,19',
      valorLiberado: 'R$50.393,84',
      saldoALiberar: 'R$7.130,35',
      inicioVigencia: '22/07/2022',
      fimVigencia: '22/07/2025',
      diasRestantes: '-24 dias restantes',
      percentualLiberado: 87.6
    },
    {
      ano: 2020,
      numero: '896731',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'CAPAGIIC Saude: Curso de aperfeicoamento em gestao, informacao, inovacao e conhecimento em saude, ob...',
      valorConvenio: 'R$11.243.543,00',
      valorLiberado: 'R$10.243.543,00',
      saldoALiberar: 'R$1.000.000,00',
      inicioVigencia: '31/01/2020',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 91.11
    },
    {
      ano: 2025,
      numero: '970149',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Implantacao do Nucleo de Formacao Continuada para Conselhos e Sistema de Garantia de Direitos no Est...',
      valorConvenio: 'R$600.000,00',
      valorLiberado: 'R$600.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '10/01/2025',
      fimVigencia: '05/05/2026',
      diasRestantes: '262 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2021,
      numero: '917020',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Projeto UFRGS Integrada: Transformacao Digital e Desenvolvimento Institucional',
      valorConvenio: 'R$2.761.072,90',
      valorLiberado: 'R$2.144.000,00',
      saldoALiberar: 'R$617.072,90',
      inicioVigencia: '08/10/2021',
      fimVigencia: '30/09/2025',
      diasRestantes: '45 dias restantes',
      percentualLiberado: 77.65
    },
    {
      ano: 2021,
      numero: '917824',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'CURSO DE EXTENSAO QUALIDADE NA EDUCACAO INFANTIL',
      valorConvenio: 'R$379.932,67',
      valorLiberado: 'R$379.932,67',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '08/11/2021',
      fimVigencia: '30/06/2025',
      diasRestantes: '-46 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '940836',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Projeto de Desenvolvimento Institucional do Instituto de Letras (2022-2024)',
      valorConvenio: 'R$282.310,46',
      valorLiberado: 'R$189.635,46',
      saldoALiberar: 'R$92.675,00',
      inicioVigencia: '01/06/2023',
      fimVigencia: '31/12/2026',
      diasRestantes: '502 dias restantes',
      percentualLiberado: 67.17
    },
    {
      ano: 2025,
      numero: '973501',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Realizacao da 2 Edicao do Inquerito domiciliar da Pesquisa Nacional sobre Acesso,Utilizacao e Promoc...',
      valorConvenio: 'R$9.025.005,40',
      valorLiberado: 'R$1.300.000,00',
      saldoALiberar: 'R$7.725.005,40',
      inicioVigencia: '15/01/2025',
      fimVigencia: '18/11/2027',
      diasRestantes: '824 dias restantes',
      percentualLiberado: 14.4
    },
    {
      ano: 2024,
      numero: '969160',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'CARACTERIZACAO E MODELAGEM DAS CHEIAS DE 2024 NO RS EM ESCALA REGIONAL',
      valorConvenio: 'R$175.591,52',
      valorLiberado: 'R$175.591,52',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '13/12/2024',
      fimVigencia: '12/06/2025',
      diasRestantes: '-64 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '967402',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'MOSTRA CINEMA NEGRO NA ESCOLA',
      valorConvenio: 'R$176.000,00',
      valorLiberado: 'R$176.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '30/08/2024',
      fimVigencia: '30/08/2025',
      diasRestantes: '14 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '972437',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Iniciativa Brasileira de Biomarcadores para Doencas Neurodegenerativas: Doenca de Alzheimer',
      valorConvenio: 'R$6.149.942,60',
      valorLiberado: 'R$600.000,00',
      saldoALiberar: 'R$5.549.942,60',
      inicioVigencia: '30/12/2024',
      fimVigencia: '16/02/2028',
      diasRestantes: '914 dias restantes',
      percentualLiberado: 9.76
    },
    {
      ano: 2025,
      numero: '971773',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO EMPRESA ESCOLA DE ENGENHARIA DA UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL FEENG',
      objeto: 'Aprimoramento de Sistema de Alerta de Cheias para o Rio Grande do Sul Hidrologico.',
      valorConvenio: 'R$2.074.390,38',
      valorLiberado: 'R$2.074.390,38',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '07/01/2025',
      fimVigencia: '09/12/2026',
      diasRestantes: '480 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2020,
      numero: '900819',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO EMPRESA ESCOLA DE ENGENHARIA DA UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL FEENG',
      objeto: 'Este projeto de extensao universitaria tem como objetivo realizar atividades de capacitacao e acompa...',
      valorConvenio: 'R$1.830.000,00',
      valorLiberado: 'R$1.830.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '18/12/2020',
      fimVigencia: '15/09/2026',
      diasRestantes: '395 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '973499',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO MEDICA DO RIO GRANDE DO SUL',
      objeto: 'O presente Projeto de Desenvolvimento Institucional (PDI) visa a qualificacao da infraestrutura e da...',
      valorConvenio: 'R$4.800.000,00',
      valorLiberado: 'R$2.500.000,00',
      saldoALiberar: 'R$2.300.000,00',
      inicioVigencia: '03/02/2025',
      fimVigencia: '03/02/2030',
      diasRestantes: '1632 dias restantes',
      percentualLiberado: 52.08
    },
    {
      ano: 2024,
      numero: '968961',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO EMPRESA ESCOLA DE ENGENHARIA DA UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL FEENG',
      objeto: 'Objeto do Convenio: Descrever o objeto a que se destina o Convenio/Contrato de Repasse de forma clar...',
      valorConvenio: 'R$175.000,00',
      valorLiberado: 'R$175.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '29/11/2024',
      fimVigencia: '10/10/2025',
      diasRestantes: '55 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '950919',
      situacao: 'NORMAL',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO EMPRESA ESCOLA DE ENGENHARIA DA UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL FEENG',
      objeto: 'Trata-se do TED 12586 para prover recurso/custeio para a realizacao de um curso de formacao continua...',
      valorConvenio: 'R$140.880,00',
      valorLiberado: 'R$140.880,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '26/01/2024',
      fimVigencia: '30/11/2024',
      diasRestantes: '-258 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '968796',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO EMPRESA ESCOLA DE ENGENHARIA DA UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL FEENG',
      objeto: 'O projeto de pesquisa Mulheres e (sub)Representacao politica no Brasil: trajetorias e enfrentamentos...',
      valorConvenio: 'R$172.020,00',
      valorLiberado: 'R$172.020,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '13/11/2024',
      fimVigencia: '13/11/2025',
      diasRestantes: '89 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2020,
      numero: '903351',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO MEDICA DO RIO GRANDE DO SUL',
      objeto: 'O presente Convenio tem por finalidade a conjugacao de esforcos para o desenvolvimento do projeto Gr...',
      valorConvenio: 'R$2.434.928,14',
      valorLiberado: 'R$2.227.932,63',
      saldoALiberar: 'R$206.995,51',
      inicioVigencia: '18/09/2020',
      fimVigencia: '31/08/2025',
      diasRestantes: '15 dias restantes',
      percentualLiberado: 91.5
    },
    {
      ano: 2024,
      numero: '971439',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO EMPRESA ESCOLA DE ENGENHARIA DA UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL FEENG',
      objeto: 'Avaliacao das avidades de negocios realizadas no ambito da terceira edicao do Mercado das Industrias...',
      valorConvenio: 'R$343.717,13',
      valorLiberado: 'R$120.000,00',
      saldoALiberar: 'R$223.717,13',
      inicioVigencia: '26/12/2024',
      fimVigencia: '03/06/2026',
      diasRestantes: '291 dias restantes',
      percentualLiberado: 34.91
    },
    {
      ano: 2024,
      numero: '969397',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: '7a Edicao do Saberes Indigenas na Escola',
      valorConvenio: 'R$100.000,00',
      valorLiberado: 'R$100.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '02/12/2024',
      fimVigencia: '30/06/2025',
      diasRestantes: '-46 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2021,
      numero: '909635',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'O presente Convenio tem por finalidade a conjugacao de esforcos para o desenvolvimento do Projeto PL...',
      valorConvenio: 'R$475.000,00',
      valorLiberado: 'R$433.518,68',
      saldoALiberar: 'R$41.481,32',
      inicioVigencia: '30/04/2021',
      fimVigencia: '30/10/2025',
      diasRestantes: '75 dias restantes',
      percentualLiberado: 91.27
    },
    {
      ano: 2022,
      numero: '934270',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'O presente Convenio tem por finalidade a conjugacao de esforcos para o desenvolvimento do Projeto de...',
      valorConvenio: 'R$450.000,00',
      valorLiberado: 'R$375.000,00',
      saldoALiberar: 'R$75.000,00',
      inicioVigencia: '30/08/2022',
      fimVigencia: '30/08/2025',
      diasRestantes: '14 dias restantes',
      percentualLiberado: 83.33
    },
    {
      ano: 2021,
      numero: '918711',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Curso Tecnico de Agente Comunitario de Saude e Curso Tecnico em Vigilancia em Saude com Enfase no Co...',
      valorConvenio: 'R$456.178.843,26',
      valorLiberado: 'R$423.864.935,00',
      saldoALiberar: 'R$32.313.908,26',
      inicioVigencia: '17/11/2021',
      fimVigencia: '31/10/2026',
      diasRestantes: '441 dias restantes',
      percentualLiberado: 92.92
    },
    {
      ano: 2023,
      numero: '952346',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'TERRITORIOS SOCIOECONOMICOS E MEIO AMBIENTE EM OSORIO/RS',
      valorConvenio: 'R$100.000,00',
      valorLiberado: 'R$100.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '20/12/2023',
      fimVigencia: '20/12/2025',
      diasRestantes: '126 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '961640',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Projeto de Desenvolvimento Institucional da Faculdade de Odontologia 2024-2026',
      valorConvenio: 'R$2.500.000,00',
      valorLiberado: 'R$1.328.333,28',
      saldoALiberar: 'R$1.171.666,72',
      inicioVigencia: '21/06/2024',
      fimVigencia: '21/06/2026',
      diasRestantes: '309 dias restantes',
      percentualLiberado: 53.13
    },
    {
      ano: 2024,
      numero: '972239',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Implementacao do Nucleo de Formacao Continuada para o Sistema Estadual Socioeducativo (SEAS) no Esta...',
      valorConvenio: 'R$500.000,00',
      valorLiberado: 'R$500.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '27/12/2024',
      fimVigencia: '09/06/2026',
      diasRestantes: '297 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2021,
      numero: '918761',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Finalidade a conjugacao de esforcos para o desenvolvimento do projeto EVENTOS DE EXTENSAO UNIVERSITA...',
      valorConvenio: 'R$2.790.000,00',
      valorLiberado: 'R$1.990.000,00',
      saldoALiberar: 'R$800.000,00',
      inicioVigencia: '18/11/2021',
      fimVigencia: '18/11/2026',
      diasRestantes: '459 dias restantes',
      percentualLiberado: 71.33
    },
    {
      ano: 2024,
      numero: '968144',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Curso de Extensao em Educacao Inclusiva: Formacao de Profissionais de Apoio',
      valorConvenio: 'R$250.000,00',
      valorLiberado: 'R$250.000,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '01/10/2024',
      fimVigencia: '01/04/2026',
      diasRestantes: '228 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2023,
      numero: '947375',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Curso de Aperfeicoamento UNIAFRO: Politica de Promocao da Igualdade Racial na Escola - 6a edicao',
      valorConvenio: 'R$276.057,25',
      valorLiberado: 'R$276.057,25',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '20/11/2023',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '973485',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Projeto de Desenvolvimento Institucional da Faculdade de Farmacia',
      valorConvenio: 'R$2.800.000,00',
      valorLiberado: 'R$10.000,00',
      saldoALiberar: 'R$2.790.000,00',
      inicioVigencia: '10/01/2025',
      fimVigencia: '10/01/2027',
      diasRestantes: '512 dias restantes',
      percentualLiberado: 0.36
    },
    {
      ano: 2024,
      numero: '968783',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Financiamento Cursos UAB - 2024/1',
      valorConvenio: 'R$394.725,00',
      valorLiberado: 'R$169.081,25',
      saldoALiberar: 'R$225.643,75',
      inicioVigencia: '27/11/2024',
      fimVigencia: '30/07/2029',
      diasRestantes: '1444 dias restantes',
      percentualLiberado: 42.84
    },
    {
      ano: 2023,
      numero: '944259',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'CENTRO COLABORADOR DE APOIO AO MONITORAMENTO E A GESTAO DEPROGRAMAS EDUCACIONAIS: 2023-2026 - CECAMP...',
      valorConvenio: 'R$8.000.000,00',
      valorLiberado: 'R$3.500.000,00',
      saldoALiberar: 'R$4.500.000,00',
      inicioVigencia: '01/09/2023',
      fimVigencia: '01/09/2027',
      diasRestantes: '746 dias restantes',
      percentualLiberado: 43.75
    },
    {
      ano: 2024,
      numero: '969151',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'ATENDIMENTO EDUCACIONAL ESPECIALIZADO NA ESCOLA BASICA: A ACESSIBILIDADE CURRICULAR COMO DIRETRIZ DA...',
      valorConvenio: 'R$214.025,88',
      valorLiberado: 'R$214.025,88',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '28/11/2024',
      fimVigencia: '31/05/2025',
      diasRestantes: '-76 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '974910',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Projeto de Desenvolvimento Institucional da Faculdade de Direito UFRGS',
      valorConvenio: 'R$672.000,00',
      valorLiberado: 'R$28.000,00',
      saldoALiberar: 'R$644.000,00',
      inicioVigencia: '19/05/2025',
      fimVigencia: '19/05/2027',
      diasRestantes: '641 dias restantes',
      percentualLiberado: 4.17
    },
    {
      ano: 2023,
      numero: '950499',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Formacao de profissionais da educacao da Educacao Infantil no ambito do Compromisso Nacional Crianca...',
      valorConvenio: 'R$25.009.355,77',
      valorLiberado: 'R$25.009.355,77',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '13/12/2023',
      fimVigencia: '31/12/2025',
      diasRestantes: '137 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2025,
      numero: '975108',
      situacao: 'EM EXECUÇÃO',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'DINTER - EDUCACAO 2025 -2030',
      valorConvenio: 'R$400.000,00',
      valorLiberado: 'R$40.000,00',
      saldoALiberar: 'R$360.000,00',
      inicioVigencia: '12/06/2025',
      fimVigencia: '17/04/2030',
      diasRestantes: '1705 dias restantes',
      percentualLiberado: 10
    },
    {
      ano: 2024,
      numero: '967821',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'CURSO DE APERFEICOAMENTO EM ORIENTACAO E MOBILIDADE, BRAILLE E AUDIODESCRICAO',
      valorConvenio: 'R$45.540,00',
      valorLiberado: 'R$45.540,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '26/09/2024',
      fimVigencia: '31/05/2025',
      diasRestantes: '-76 dias restantes',
      percentualLiberado: 100
    },
    {
      ano: 2024,
      numero: '969617',
      situacao: 'AGUARDANDO PRESTAÇÃO DE CONTAS',
      uf: 'RS',
      municipio: 'PORTO ALEGRE',
      proponente: 'Universidade Federal do Rio Grande do Sul',
      convenente: 'FUNDACAO DE APOIO DA UNIVERSIDADE FEDERAL DO RGS',
      objeto: 'Projeto de traducao para a Libras - Lingua Brasileira de Sinais no evento G20',
      valorConvenio: 'R$51.600,00',
      valorLiberado: 'R$51.600,00',
      saldoALiberar: 'R$0,00',
      inicioVigencia: '05/12/2024',
      fimVigencia: '05/06/2025',
      diasRestantes: '-71 dias restantes',
      percentualLiberado: 100
    }
];


    