

export const users = [
  { id: 1, name: 'Alice', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Ok, vou verificar.', lastMessageTime: '10:40 AM', unread: 2 },
  { id: 2, name: 'Carlos', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'O relatório está pronto.', lastMessageTime: '9:30 AM', unread: 0 },
  { id: 3, name: 'Beatriz', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Podemos marcar uma reunião?', lastMessageTime: 'Ontem', unread: 0 },
  { id: 4, name: 'Daniel', avatar: 'https://placehold.co/40x40.png', online: true, lastMessage: 'Anexei os documentos.', lastMessageTime: 'Ontem', unread: 1 },
  { id: 5, name: 'Fernanda', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'Qual o prazo final?', lastMessageTime: '2 dias atrás', unread: 0 },
  { id: 6, name: 'Gustavo', avatar: 'https://placehold.co/40x40.png', online: false, lastMessage: 'Entendido.', lastMessageTime: '2 dias atrás', unread: 0 },
];

export const messages = {
  '1': [
    { sender: 'me', text: 'Olá Alice, tudo bem? Conseguiu ver a documentação da emenda parlamentar?', timestamp: '10:30 AM' },
    { sender: 'Alice', text: 'Oi! Tudo bem. Sim, estou analisando agora.', timestamp: '10:32 AM' },
    { sender: 'Alice', text: 'Parece que falta a assinatura do gestor. Você pode confirmar?', timestamp: '10:35 AM' },
    { sender: 'me', text: 'Claro, vou checar com ele e te retorno.', timestamp: '10:36 AM' },
    { sender: 'Alice', text: 'Ok, vou verificar.', timestamp: '10:40 AM' },
  ],
  '2': [
    { sender: 'Carlos', text: 'O relatório está pronto.', timestamp: '9:30 AM' },
  ],
  '3': [
      { sender: 'Beatriz', text: 'Podemos marcar uma reunião?', timestamp: 'Ontem' },
  ]
};

export const conventions = [
  {
      ano: 2013,
      numero: '677800',
      situacao: 'ADIMPLENTE',
      uf: 'DF',
      municipio: 'BRASÍLIA',
      proponente: 'VALEC Engenharia, Construções e Ferrovias SA',
      convenente: 'VALEC ENGENHARIA, CONSTRUÇÕES E FERROVIAS SA',
      objeto: 'FORTALECIMENTO INSTITUCIONAL DA EMPRESA DE PLANEJAMENTO E LOGÍSTICA POR MEIO DA PROPOSIÇÃO DE MODE...',
      valorConvenio: 'R$ 58.991.596,21',
      valorLiberado: 'R$ 53.447.422,80',
      saldoALiberar: 'R$ 5.544.173,41',
      inicioVigencia: '26/12/2013',
      fimVigencia: '31/12/2025',
      diasRestantes: 'Restam 141 dias',
      percentualLiberado: 90.60
  },
  {
      ano: 2021,
      numero: '1AAGNZ',
      situacao: 'ADIMPLENTE',
      uf: 'SP',
      municipio: 'SÃO PAULO',
      proponente: 'VALEC Engenharia, Construções e Ferrovias SA',
      convenente: 'CFI - CORPORAÇÃO FINANCEIRA INTERNACIONAL',
      objeto: 'ACORDO DE PARCERIA 01/2021-ELABORAÇÃO DE ESTUDOS DE VIABILIDADE TÉCNICA, ECONÔMICO-FINANCEIRA, AMBIE...',
      valorConvenio: 'R$ 21.154.683,15',
      valorLiberado: 'R$ 15.412.716,03',
      saldoALiberar: 'R$ 5.741.967,12',
      inicioVigencia: '29/11/2021',
      fimVigencia: '29/06/2026',
      diasRestantes: '321 dias restantes',
      percentualLiberado: 72.86
  },
  {
      ano: 2021,
      numero: '1AAHAF',
      situacao: 'ADIMPLENTE',
      uf: 'DF',
      municipio: 'BRASÍLIA',
      proponente: 'VALEC Engenharia, Construções e Ferrovias SA',
      convenente: 'BANCO INTERAMERICANO DE DESENVOLVIMENTO',
      objeto: 'ACORDO DE PARCERIA 02/2021 PARA ELABORAR ESTUDOS DE VIABILIDADE TÉCNICA, ECONÔMICO-FINANCEIRA, AMBIE...',
      valorConvenio: 'R$ 30.804.079,98',
      valorLiberado: 'R$ 14.347.545,54',
      saldoALiberar: 'R$ 16.456.534,44',
      inicioVigencia: '15/12/2021',
      fimVigencia: '15/06/2027',
      diasRestantes: '672 dias restantes',
      percentualLiberado: 46.58
  },
  {
      ano: 2025,
      numero: '976278',
      situacao: 'EM EXECUÇÃO',
      uf: 'RP',
      municipio: 'CURITIBA',
      proponente: 'Universidade Tecnológica Federal do Paraná',
      convenente: 'FUNDAÇÃO DE APOIO A EDUCAÇÃO, PESQUISA E DESENVOLVIMENTO',
      objeto: 'Oferta de Turma de Mestrado Interinstitucional Minter em Planejamento e Governança Pública, devida...',
      valorConvenio: 'R$ 740.827,50',
      valorLiberado: 'R$ 200.000,00',
      saldoALiberar: 'R$ 540.827,50',
      inicioVigencia: '29/07/2025',
      fimVigencia: '13/03/2028',
      diasRestantes: 'Restam 944 dias',
      percentualLiberado: 27.00
  },
  {
      ano: 2024,
      numero: '937124',
      situacao: 'EM EXECUÇÃO',
      uf: 'RP',
      municipio: 'CURITIBA',
      proponente: 'Universidade Tecnológica Federal do Paraná',
      convenente: 'FUNDAÇÃO DE APOIO A EDUCAÇÃO, PESQUISA E DESENVOLVIMENTO',
      objeto: 'Execução do TED 04/2022 junto à Funasa - Apoio à elaboração de Planos de Segurança da Água (PSA) par...',
      valorConvenio: 'R$ 976.636,62',
      valorLiberado: 'R$ 782.285,94',
      saldoALiberar: 'R$ 194.350,68',
      inicioVigencia: '19/03/2024',
      fimVigencia: '07/07/2026',
      diasRestantes: 'Restam 329 dias',
      percentualLiberado: 80.10
  },
  {
      ano: 2023,
      numero: '940849',
      situacao: 'PRESTAÇÃO DE CONTAS EM ANÁLISE',
      uf: 'RN',
      municipio: 'MOSSORÓ',
      proponente: 'Universidade Federal Rural do Semi-Árido',
      convenente: 'FUNDAÇÃO GUIMARÃES DUQUE',
      objeto: 'Oferecer curso de qualificação profissional na região semiárida potiguar, promovendo a qualificação...',
      valorConvenio: 'R$ 1.000.000,00',
      valorLiberado: 'R$ 795.139,84',
      saldoALiberar: 'R$ 204.860,16',
      inicioVigencia: '01/06/2023',
      fimVigencia: '31/03/2025',
      diasRestantes: '-133 dias restantes',
      percentualLiberado: 79.51
  },
];

export const amendments = [
  { 
    id: '201830490006',
    ano: 2018,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0006',
    localidade: 'Nacional',
    funcao: 'Saúde',
    subfuncao: 'Assistência hospitalar e ambulatorial',
    valorEmpenhado: 'R$ 100.000,00',
    valor: 'R$ 100.000,00',
    valorPago: 'R$ 100.000,00',
    valorLiberar: 'R$ 0,00',
    porcentagem: 100,
    status: 'Aprovada'
  },
  { 
    id: '201830490004',
    ano: 2018,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0004',
    localidade: 'RORAIMA (UF)',
    funcao: 'Saúde',
    subfuncao: 'Administração geral',
    valorEmpenhado: 'R$ 6.486.136,00',
     valor: 'R$ 6.486.136,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 6.486.136,00',
    porcentagem: 0,
    status: 'Rejeitada'
  },
  { 
    id: '201930490003',
    ano: 2019,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0003',
    localidade: 'RORAIMA (UF)',
    funcao: 'Saúde',
    subfuncao: 'Assistência hospitalar e ambulatorial',
    valorEmpenhado: 'R$ 7.610.387,00',
    valor: 'R$ 7.610.387,00',
    valorPago: 'R$ 7.610.387,00',
    valorLiberar: 'R$ 0,00',
    porcentagem: 100,
    status: 'Aprovada'
  },
  { 
    id: '201630300002',
    ano: 2016,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0002',
    localidade: 'MÚLTIPLO',
    funcao: 'Urbanismo',
    subfuncao: 'Assistência comunitária',
    valorEmpenhado: 'R$ 342.143,00',
    valor: 'R$ 342.143,00',
    valorPago: 'R$ 171.071,00',
    valorLiberar: 'R$ 171.072,00',
    porcentagem: 50,
    status: 'Em análise'
  },
  { 
    id: '201730490002',
    ano: 2017,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0002',
    localidade: 'MÚLTIPLO',
    funcao: 'Saúde',
    subfuncao: 'Saneamento básico urbano',
    valorEmpenhado: 'R$ 2.343.887,00',
    valor: 'R$ 2.343.887,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 2.343.887,00',
    porcentagem: 0,
    status: 'Pendente'
  },
  {
    id: '201830490005',
    ano: 2018,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0005',
    localidade: 'RORAIMA (UF)',
    funcao: 'Saúde',
    subfuncao: 'Atenção básica',
    valorEmpenhado: 'R$ 799.942,00',
    valor: 'R$ 799.942,00',
    valorPago: 'R$ 196.000,00',
    valorLiberar: 'R$ 603.942,00',
    porcentagem: 24.5,
    status: 'Em análise'
  },
  {
    id: '201930490001',
    ano: 2019,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0001',
    localidade: 'RORAIMA (UF)',
    funcao: 'Defesa nacional',
    subfuncao: 'Assistência comunitária',
    valorEmpenhado: 'R$ 7.610.387,00',
    valor: 'R$ 7.610.387,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 7.610.387,00',
    porcentagem: 0,
    status: 'Rejeitada'
  },
  {
    id: '201730490003',
    ano: 2017,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0003',
    localidade: 'Nacional',
    funcao: 'Saúde',
    subfuncao: 'Assistência hospitalar e ambulatorial',
    valorEmpenhado: 'R$ 100.000,00',
    valor: 'R$ 100.000,00',
    valorPago: 'R$ 100.000,00',
    valorLiberar: 'R$ 0,00',
    porcentagem: 100,
    status: 'Aprovada'
  },
  {
    id: '201730490004',
    ano: 2017,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0004',
    localidade: 'MÚLTIPLO',
    funcao: 'Saúde',
    subfuncao: 'Saneamento básico rural',
    valorEmpenhado: 'R$ 4.092.563,00',
    valor: 'R$ 4.092.563,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 4.092.563,00',
    porcentagem: 0,
    status: 'Pendente'
  },
  {
    id: '201630300001',
    ano: 2016,
    tipo: 'Emenda Individual - Transferências com Finalidade Definida',
    autor: 'ABEL MESQUITA JR.',
    numero: '0001',
    localidade: 'RORAIMA (UF)',
    funcao: 'Defesa nacional',
    subfuncao: 'Assistência comunitária',
    valorEmpenhado: 'R$ 6.471.218,00',
    valor: 'R$ 6.471.218,00',
    valorPago: 'R$ 0,00',
    valorLiberar: 'R$ 6.471.218,00',
    porcentagem: 0,
    status: 'Rejeitada'
  }
];

export const senators = [
    {
      "id": "5996",
      "nome": "Alan Rick",
      "partido": "UNIÃO",
      "uf": "AC",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6333",
      "email": "sen.alanrick@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5996.jpg"
    },
    {
      "id": "5978",
      "nome": "Alessandro Vieira",
      "partido": "MDB",
      "uf": "SE",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-9011 / 9014 / 9019",
      "email": "sen.alessandrovieira@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5978.jpg"
    },
    {
      "id": "6468",
      "nome": "Ana Paula Lobato",
      "partido": "PDT",
      "uf": "MA",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-2967",
      "email": "sen.anapaulalobato@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6468.jpg"
    },
    {
      "id": "5980",
      "nome": "Angelo Coronel",
      "partido": "PSD",
      "uf": "BA",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6103 / 6105",
      "email": "sen.angelocoronel@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5980.jpg"
    },
    {
      "id": "6395",
      "nome": "Astronauta Marcos Pontes",
      "partido": "PL",
      "uf": "SP",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-1177 / 1797",
      "email": "sen.astronautamarcospontes@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6395.jpg"
    },
    {
      "id": "6463",
      "nome": "Augusta Brito",
      "partido": "PT",
      "uf": "CE",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-5940",
      "email": "sen.augustabrito@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6463.jpg"
    },
    {
      "id": "6429",
      "nome": "Beto Faro",
      "partido": "PT",
      "uf": "PA",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-5220",
      "email": "sen.betofaro@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6429.jpg"
    },
    {
      "id": "6133",
      "nome": "Carlos Portinho",
      "partido": "PL",
      "uf": "RJ",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6640 / 6613",
      "email": "sen.carlosportinho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6133.jpg"
    },
    {
      "id": "5936",
      "nome": "Carlos Viana",
      "partido": "PODEMOS",
      "uf": "MG",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-3100 / 3116",
      "email": "sen.carlosviana@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5936.jpg"
    },
    {
      "id": "5981",
      "nome": "Chico Rodrigues",
      "partido": "PSB",
      "uf": "RR",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2281",
      "email": "sen.chicorodrigues@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5981.jpg"
    },
    {
      "id": "5982",
      "nome": "Cid Gomes",
      "partido": "PSB",
      "uf": "CE",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6460 / 6399",
      "email": "sen.cidgomes@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5982.jpg"
    },
    {
      "id": "33",
      "nome": "Ciro Nogueira",
      "partido": "PP",
      "uf": "PI",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6187 / 6188 / 6183",
      "email": "sen.cironogueira@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador33.jpg"
    },
    {
      "id": "6432",
      "nome": "Cleitinho",
      "partido": "REPUBLICANOS",
      "uf": "MG",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-3811",
      "email": "sen.cleitinho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6432.jpg"
    },
    {
      "id": "5983",
      "nome": "Confúcio Moura",
      "partido": "MDB",
      "uf": "RO",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2470 / 2163",
      "email": "sen.confuciomoura@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5983.jpg"
    },
    {
      "id": "6450",
      "nome": "Damares Alves",
      "partido": "REPUBLICANOS",
      "uf": "DF",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-3265",
      "email": "sen.damaresalves@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6450.jpg"
    },
    {
      "id": "5937",
      "nome": "Daniella Ribeiro",
      "partido": "PP",
      "uf": "PB",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6788 / 6790",
      "email": "sen.daniellaribeiro@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5937.jpg"
    },
    {
      "id": "5569",
      "nome": "Davi Alcolumbre",
      "partido": "UNIÃO",
      "uf": "AP",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6717 / 6720",
      "email": "sen.davialcolumbre@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5569.jpg"
    },
    {
      "id": "6443",
      "nome": "Dr. Hiran",
      "partido": "PP",
      "uf": "RR",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6251",
      "email": "sen.drhiran@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6443.jpg"
    },
    {
      "id": "6131",
      "nome": "Dra. Eudócia",
      "partido": "PL",
      "uf": "AL",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6083",
      "email": "sen.draeudocia@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6131.jpg"
    },
    {
      "id": "70",
      "nome": "Eduardo Braga",
      "partido": "MDB",
      "uf": "AM",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6230",
      "email": "sen.eduardobraga@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador70.jpg"
    },
    {
      "id": "5941",
      "nome": "Eduardo Girão",
      "partido": "NOVO",
      "uf": "CE",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6677 / 6678 / 6679",
      "email": "sen.eduardogirao@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5941.jpg"
    },
    {
      "id": "5984",
      "nome": "Eduardo Gomes",
      "partido": "PL",
      "uf": "TO",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6349 / 6352",
      "email": "sen.eduardogomes@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5984.jpg"
    },
    {
      "id": "6446",
      "nome": "Efraim Filho",
      "partido": "UNIÃO",
      "uf": "PB",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-5934 / 5931",
      "email": "sen.efraimfilho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6446.jpg"
    },
    {
      "id": "5985",
      "nome": "Eliziane Gama",
      "partido": "PSD",
      "uf": "MA",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6741",
      "email": "sen.elizianegama@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5985.jpg"
    },
    {
      "id": "5942",
      "nome": "Esperidião Amin",
      "partido": "PP",
      "uf": "SC",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6446 / 6447 / 6454",
      "email": "sen.esperidiaoamin@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5942.jpg"
    },
    {
      "id": "5986",
      "nome": "Fabiano Contarato",
      "partido": "PT",
      "uf": "ES",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-9054 / 6743",
      "email": "sen.fabianocontarato@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5986.jpg"
    },
    {
      "id": "6376",
      "nome": "Fernando Dueire",
      "partido": "MDB",
      "uf": "PE",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-3522",
      "email": "sen.fernandodueire@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6376.jpg"
    },
    {
      "id": "6459",
      "nome": "Fernando Farias",
      "partido": "MDB",
      "uf": "AL",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6266 / 6273",
      "email": "sen.fernandofarias@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6459.jpg"
    },
    {
      "id": "5943",
      "nome": "Flávio Arns",
      "partido": "PSB",
      "uf": "PR",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6301",
      "email": "sen.flavioarns@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5943.jpg"
    },
    {
      "id": "5987",
      "nome": "Flávio Bolsonaro",
      "partido": "PL",
      "uf": "RJ",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-1717 / 1718",
      "email": "sen.flaviobolsonaro@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5987.jpg"
    },
    {
      "id": "6375",
      "nome": "Giordano",
      "partido": "MDB",
      "uf": "SP",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-4177",
      "email": "sen.giordano@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6375.jpg"
    },
    {
      "id": "6441",
      "nome": "Hamilton Mourão",
      "partido": "REPUBLICANOS",
      "uf": "RS",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-1837",
      "email": "sen.hamiltonmourao@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6441.jpg"
    },
    {
      "id": "5008",
      "nome": "Humberto Costa",
      "partido": "PT",
      "uf": "PE",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6285 / 6286",
      "email": "sen.humbertocosta@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5008.jpg"
    },
    {
      "id": "5988",
      "nome": "Irajá",
      "partido": "PSD",
      "uf": "TO",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6469 / 6474",
      "email": "sen.iraja@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5988.jpg"
    },
    {
      "id": "6372",
      "nome": "Ivete da Silveira",
      "partido": "MDB",
      "uf": "SC",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2200",
      "email": "sen.ivetedasilveira@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6372.jpg"
    },
    {
      "id": "5944",
      "nome": "Izalci Lucas",
      "partido": "PL",
      "uf": "DF",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6049 / 6050",
      "email": "sen.izalcilucas@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5944.jpg"
    },
    {
      "id": "4988",
      "nome": "Jader Barbalho",
      "partido": "MDB",
      "uf": "PA",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-9831 / 9827 / 9832",
      "email": "sen.jaderbarbalho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador4988.jpg"
    },
    {
      "id": "6444",
      "nome": "Jaime Bagattoli",
      "partido": "PL",
      "uf": "RO",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-2714",
      "email": "sen.jaimebagattoli@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6444.jpg"
    },
    {
      "id": "5989",
      "nome": "Jaques Wagner",
      "partido": "PT",
      "uf": "BA",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6390 / 6391",
      "email": "sen.jaqueswagner@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5989.jpg"
    },
    {
      "id": "5990",
      "nome": "Jayme Campos",
      "partido": "UNIÃO",
      "uf": "MT",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2390 / 2384 / 2394",
      "email": "sen.jaymecampos@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5990.jpg"
    },
    {
      "id": "5991",
      "nome": "Jorge Kajuru",
      "partido": "PSB",
      "uf": "GO",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2844 / 2031",
      "email": "sen.jorgekajuru@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5991.jpg"
    },
    {
      "id": "6423",
      "nome": "Jorge Seif",
      "partido": "PL",
      "uf": "SC",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-3784 / 3756",
      "email": "sen.jorgeseif@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6423.jpg"
    },
    {
      "id": "6464",
      "nome": "Jussara Lima",
      "partido": "PSD",
      "uf": "PI",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-5800",
      "email": "sen.jussaralima@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6464.jpg"
    },
    {
      "id": "6440",
      "nome": "Laércio Oliveira",
      "partido": "PP",
      "uf": "SE",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-1763 / 1764",
      "email": "sen.laerciooliveira@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6440.jpg"
    },
    {
      "id": "5945",
      "nome": "Leila Barros",
      "partido": "PDT",
      "uf": "DF",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6427",
      "email": "sen.leilabarros@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5945.jpg"
    },
    {
      "id": "5953",
      "nome": "Lucas Barreto",
      "partido": "PSD",
      "uf": "AP",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-4851",
      "email": "sen.lucasbarreto@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5953.jpg"
    },
    {
      "id": "5954",
      "nome": "Luis Carlos Heinze",
      "partido": "PP",
      "uf": "RS",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-4124 / 4127 / 4129 / 4132",
      "email": "sen.luiscarlosheinze@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5954.jpg"
    },
    {
      "id": "5104",
      "nome": "Magno Malta",
      "partido": "PL",
      "uf": "ES",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6370",
      "email": "sen.magnomalta@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5104.jpg"
    },
    {
      "id": "5955",
      "nome": "Mara Gabrilli",
      "partido": "PSD",
      "uf": "SP",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2191",
      "email": "sen.maragabrilli@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5955.jpg"
    },
    {
      "id": "5992",
      "nome": "Marcelo Castro",
      "partido": "MDB",
      "uf": "PI",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6130 / 4078",
      "email": "sen.marcelocastro@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5992.jpg"
    },
    {
      "id": "5956",
      "nome": "Marcio Bittar",
      "partido": "UNIÃO",
      "uf": "AC",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2115 / 2119 / 1652",
      "email": "sen.marciobittar@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5956.jpg"
    },
    {
      "id": "5993",
      "nome": "Marcos do Val",
      "partido": "PODEMOS",
      "uf": "ES",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6747 / 6753",
      "email": "sen.marcosdoval@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5993.jpg"
    },
    {
      "id": "5957",
      "nome": "Marcos Rogério",
      "partido": "PL",
      "uf": "RO",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6148",
      "email": "sen.marcosrogerio@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5957.jpg"
    },
    {
      "id": "6369",
      "nome": "Margareth Buzetti",
      "partido": "PSD",
      "uf": "MT",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6408",
      "email": "sen.margarethbuzetti@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6369.jpg"
    },
    {
      "id": "5958",
      "nome": "Mecias de Jesus",
      "partido": "REPUBLICANOS",
      "uf": "RR",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-5291 / 5292",
      "email": "sen.meciasdejesus@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5958.jpg"
    },
    {
      "id": "5959",
      "nome": "Nelsinho Trad",
      "partido": "PSD",
      "uf": "MS",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6767 / 6768",
      "email": "sen.nelsinhotrad@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5959.jpg"
    },
    {
      "id": "5582",
      "nome": "Omar Aziz",
      "partido": "PSD",
      "uf": "AM",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6579 / 6581",
      "email": "sen.omaraziz@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5582.jpg"
    },
    {
      "id": "5994",
      "nome": "Oriovisto Guimarães",
      "partido": "PSDB",
      "uf": "PR",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-1635",
      "email": "sen.oriovistoguimaraes@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5994.jpg"
    },
    {
      "id": "5190",
      "nome": "Otto Alencar",
      "partido": "PSD",
      "uf": "BA",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-3172 / 1464 / 1467",
      "email": "sen.ottoalencar@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5190.jpg"
    },
    {
      "id": "590",
      "nome": "Paulo Paim",
      "partido": "PT",
      "uf": "RS",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-5232 / 5231 / 5230 / 5235",
      "email": "sen.paulopaim@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador590.jpg"
    },
    {
      "id": "5803",
      "nome": "Pedro Chaves",
      "partido": "MDB",
      "uf": "GO",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2092 / 2099",
      "email": "",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5803.jpg"
    },
    {
      "id": "5960",
      "nome": "Plínio Valério",
      "partido": "PSDB",
      "uf": "AM",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2898 / 2800",
      "email": "sen.pliniovalerio@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5960.jpg"
    },
    {
      "id": "6442",
      "nome": "Professora Dorinha Seabra",
      "partido": "UNIÃO",
      "uf": "TO",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-5990 / 5995 / 5900",
      "email": "sen.professoradorinhaseabra@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6442.jpg"
    },
    {
      "id": "5070",
      "nome": "Randolfe Rodrigues",
      "partido": "PT",
      "uf": "AP",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6777 / 6568",
      "email": "sen.randolferodrigues@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5070.jpg"
    },
    {
      "id": "615",
      "nome": "Renan Calheiros",
      "partido": "MDB",
      "uf": "AL",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2261 / 2262 / 2265 / 2268",
      "email": "sen.renancalheiros@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador615.jpg"
    },
    {
      "id": "5961",
      "nome": "Rodrigo Pacheco",
      "partido": "PSD",
      "uf": "MG",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2794",
      "email": "sen.rodrigopacheco@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5961.jpg"
    },
    {
      "id": "5962",
      "nome": "Rogério Carvalho",
      "partido": "PT",
      "uf": "SE",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2201 / 2203",
      "email": "sen.rogeriocarvalho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5962.jpg"
    },
    {
      "id": "6428",
      "nome": "Rogerio Marinho",
      "partido": "PL",
      "uf": "RN",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-1826",
      "email": "sen.rogeriomarinho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6428.jpg"
    },
    {
      "id": "5563",
      "nome": "Romário",
      "partido": "PL",
      "uf": "RJ",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6519 / 6517",
      "email": "sen.romario@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5563.jpg"
    },
    {
      "id": "6438",
      "nome": "Sergio Moro",
      "partido": "UNIÃO",
      "uf": "PR",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6202",
      "email": "sen.sergiomoro@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6438.jpg"
    },
    {
      "id": "5012",
      "nome": "Sérgio Petecão",
      "partido": "PSD",
      "uf": "AC",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-4086 / 6708 / 6709",
      "email": "sen.sergiopetecao@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5012.jpg"
    },
    {
      "id": "5963",
      "nome": "Soraya Thronicke",
      "partido": "PODEMOS",
      "uf": "MS",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-1775",
      "email": "sen.sorayathronicke@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5963.jpg"
    },
    {
      "id": "5977",
      "nome": "Styvenson Valentim",
      "partido": "PSDB",
      "uf": "RN",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-1148",
      "email": "sen.styvensonvalentim@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5977.jpg"
    },
    {
      "id": "6453",
      "nome": "Teresa Leitão",
      "partido": "PT",
      "uf": "PE",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-2423",
      "email": "sen.teresaleitao@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6453.jpg"
    },
    {
      "id": "6431",
      "nome": "Tereza Cristina",
      "partido": "PP",
      "uf": "MS",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-2431",
      "email": "sen.terezacristina@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6431.jpg"
    },
    {
      "id": "5979",
      "nome": "Veneziano Vital do Rêgo",
      "partido": "MDB",
      "uf": "PB",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2252 / 2481",
      "email": "sen.venezianovitaldorego@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5979.jpg"
    },
    {
      "id": "5657",
      "nome": "Wellington Fagundes",
      "partido": "PL",
      "uf": "MT",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6219 / 3778 / 3772 / 6209 / 6213 / 3775",
      "email": "sen.wellingtonfagundes@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5657.jpg"
    },
    {
      "id": "5964",
      "nome": "Weverton",
      "partido": "PDT",
      "uf": "MA",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-4161 / 1655",
      "email": "sen.wevertonrocha@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5964.jpg"
    },
    {
      "id": "6445",
      "nome": "Wilder Morais",
      "partido": "PL",
      "uf": "GO",
      "periodo": "2023 - 2031",
      "telefones": "(61) 3303-6440",
      "email": "sen.wildermorais@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador6445.jpg"
    },
    {
      "id": "5965",
      "nome": "Zenaide Maia",
      "partido": "PSD",
      "uf": "RN",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-2371 / 2372 / 2358",
      "email": "sen.zenaidemaia@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5965.jpg"
    },
    {
      "id": "5966",
      "nome": "Zequinha Marinho",
      "partido": "PODEMOS",
      "uf": "PA",
      "periodo": "2019 - 2027",
      "telefones": "(61) 3303-6623",
      "email": "sen.zequinhamarinho@senado.leg.br",
      "foto": "https://www.senado.leg.br/senadores/img/fotos-oficiais/senador5966.jpg"
    }
]
