{
  "name": "integrador-api",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "npm-run-all --parallel \"dev:* -- {1}\" --",
    "dev:next": "next dev",
    "dev:api": "ts-node-dev --respawn --transpile-only src/api/index.ts",
    "build": "npm-run-all build:*",
    "build:next": "next build",
    "build:api": "tsc -p api/tsconfig.json",
    "start": "npm-run-all --parallel \"start:* -- {1}\" --",
    "start:next": "next start",
    "start:api": "node dist/api/index.js",
    "lint": "next lint",
    "seed": "node -r dotenv/config ./scripts/seed.js"
  },
  "dependencies": {
    "@genkit-ai/firebase": "^1.14.1",
    "@genkit-ai/googleai": "^1.14.1",
    "@genkit-ai/next": "^1.14.1",
    "@hookform/resolvers": "^4.1.3",
    "@radix-ui/react-accordion": "^1.2.3",
    "@radix-ui/react-alert-dialog": "^1.1.6",
    "@radix-ui/react-avatar": "^1.1.3",
    "@radix-ui/react-checkbox": "^1.1.4",
    "@radix-ui/react-collapsible": "^1.1.11",
    "@radix-ui/react-dialog": "^1.1.6",
    "@radix-ui/react-dropdown-menu": "^2.1.6",
    "@radix-ui/react-label": "^2.1.2",
    "@radix-ui/react-menubar": "^1.1.6",
    "@radix-ui/react-popover": "^1.1.6",
    "@radix-ui/react-progress": "^1.1.2",
    "@radix-ui/react-radio-group": "^1.2.3",
    "@radix-ui/react-scroll-area": "^1.2.3",
    "@radix-ui/react-select": "^2.1.6",
    "@radix-ui/react-separator": "^1.1.2",
    "@radix-ui/react-slider": "^1.2.3",
    "@radix-ui/react-slot": "^1.2.3",
    "@radix-ui/react-switch": "^1.1.3",
    "@radix-ui/react-tabs": "^1.1.3",
    "@radix-ui/react-toast": "^1.2.6",
    "@radix-ui/react-tooltip": "^1.1.8",
    "@vercel/postgres": "^0.9.0",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "cors": "^2.8.5",
    "date-fns": "^3.6.0",
    "dotenv": "^16.5.0",
    "embla-carousel-react": "^8.6.0",
    "express": "^4.18.2",
    "express-rate-limit": "^6.10.0",
    "firebase": "^11.9.1",
    "genkit": "^1.14.1",
    "helmet": "^7.0.0",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.8.2",
    "lucide-react": "^0.475.0",
    "next": "15.3.3",
    "node-fetch": "^3.3.2",
    "npm-run-all": "^4.1.5",
    "patch-package": "^8.0.0",
    "pg": "^8.12.0",
    "react": "^18.3.1",
    "react-day-picker": "^8.10.1",
    "react-dom": "^18.3.1",
    "react-hook-form": "^7.54.2",
    "recharts": "^2.15.1",
    "tailwind-merge": "^3.0.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.24.2"
  },
  "devDependencies": {
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.17",
    "@types/jspdf": "^2.0.0",
    "@types/node": "^20",
    "@types/pg": "^8.11.6",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "genkit-cli": "^1.14.1",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5"
  }
}